/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Schedule;

import TableView.TableTKBMH;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.GiaoVien;
import models.MonHoc;
import models.TKBMH;
import services.Services;
import utilis.BackHome;
import utilis.CenterScreen;
import utilis.CommonUtilis;
import utilis.ProtectScreen;
import view.AdminQLMH.QLMHScreen;

/**
 *
 * @author XuanHoang
 */
public class ScheduleScreen extends javax.swing.JFrame {

    ArrayList<TKBMH> dsTKBMH = new ArrayList<>();
    ArrayList<MonHoc> dsMonHoc = new ArrayList<>();
    ArrayList<GiaoVien> dsGiaoVien = new ArrayList<>();

    /**
     * Creates new form ScheduleScreen
     */
    public ScheduleScreen() {
        initComponents();
        fetchDataCB();
        LoadTableSchedule();
    }

    public void LoadTableSchedule() {
        tableTKBMH.setModel(new TableTKBMH(dsTKBMH));

    }

    public void fetchDataCB() {
        try {
            String sql = "SELECT  mon_hoc.id,mon_hoc.name,mon_hoc.so_tin_chi,nhom_mon.name "
                    + "as ten_nhom FROM `mon_hoc` INNER JOIN nhom_mon ON mon_hoc.id_nhom = nhom_mon.id\n";
            ResultSet rs = services.Services.get(sql);
            MonHoc x = null;
            while (rs.next()) {
                x = new MonHoc(rs.getInt("mon_hoc.id"), rs.getString("mon_hoc.name"), rs.getInt("mon_hoc.so_tin_chi"),
                        rs.getString("ten_nhom"));
                dsMonHoc.add(x);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        for (MonHoc monHoc : dsMonHoc) {
            cbMonHoc.addItem(monHoc.getName());
        }

        try {
            String sql = "SELECT `id`, `name`, `address`, `phone` FROM `giao_vien` WHERE 1";
            ResultSet rs = Services.get(sql);
            GiaoVien x = null;
            while (rs.next()) {
                x = new GiaoVien(rs.getInt("id"), rs.getString("name"), rs.getString("address"), rs.getString("phone"));
                dsGiaoVien.add(x);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }

        for (GiaoVien giaoVien : dsGiaoVien) {
            cbGiaoVien.addItem(giaoVien.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTKBMH = new javax.swing.JTable();
        btnDeleteItem = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbMonHoc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtMinHS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaxHS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSoPhong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbGiaoVien = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtSoTuan = new javax.swing.JTextField();
        txtTimeStart = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("TKB các môn");

        tableTKBMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableTKBMH);

        btnDeleteItem.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteItem.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteItem.setText("Xóa");
        btnDeleteItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        btnBack.setText("Quay lại");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("Tạo TKB cho môn học mới");

        jLabel3.setText("Môn học: ");

        cbMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonHocActionPerformed(evt);
            }
        });

        jLabel4.setText("Số HS tối thiểu");

        jLabel5.setText("Số HS tối đa");

        jLabel6.setText("Thời gian bắt đầu");

        jLabel7.setText("Số phòng");

        jLabel8.setText("Tên giáo viên");

        jLabel9.setText("Số tuần học");

        btnAddItem.setBackground(java.awt.Color.green);
        btnAddItem.setForeground(new java.awt.Color(255, 255, 255));
        btnAddItem.setText("Tạo");
        btnAddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbMonHoc, 0, 155, Short.MAX_VALUE)
                                        .addComponent(txtMinHS)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTimeStart)
                                        .addComponent(txtMaxHS, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))
                            .addComponent(jLabel1))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoPhong)
                                    .addComponent(cbGiaoVien, 0, 156, Short.MAX_VALUE)
                                    .addComponent(txtSoTuan)))
                            .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMinHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaxHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSoTuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAddItem))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteItem)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        BackHome.admin(this);
    }// GEN-LAST:event_btnBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fetchData();
    }// GEN-LAST:event_formWindowOpened

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
        try {
            int row = tableTKBMH.getSelectedRow();
            // lấy id của khoa cần xóa
            int idDelete;
            idDelete = (int) tableTKBMH.getModel().getValueAt(row, 0);
            try {
                String sql = "DELETE FROM `tkb_mh` WHERE id = " + idDelete;
                services.Services.post(sql);
                fetchData();
            } catch (Exception ex) {
                System.out.println(ex);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Yêu cầu chọn môn học để xóa !",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnDeleteItemActionPerformed

    private void cbMonHocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbMonHocActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_cbMonHocActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        String ten_mon = (String) cbMonHoc.getSelectedItem();
        String min_sv = txtMinHS.getText();
        String max_sv = txtMaxHS.getText();
        String time_start = txtTimeStart.getText();
        String so_phong = txtSoPhong.getText();
        String ten_giao_vien = (String) cbGiaoVien.getSelectedItem();
        String so_tuan_hoc = txtSoTuan.getText();

        if (ten_mon.equals("") || min_sv.equals("") || max_sv.equals("") || time_start.equals("")
                || so_phong.equals("") || ten_giao_vien.equals("") || so_tuan_hoc.equals("")) {
            JOptionPane.showMessageDialog(this, "Yêu cầu nhập đủ các trường !",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!CommonUtilis.isNumeric(min_sv) || !CommonUtilis.isNumeric(max_sv) || !CommonUtilis.isNumeric(so_tuan_hoc)) {
            JOptionPane.showMessageDialog(this, "Yêu cầu số lượng HS tối thiểu, tối đa, số tuần học"
                    + " phải là số !",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int id_mon_hoc = 0;
        for (MonHoc monHoc : dsMonHoc) {
            if (ten_mon.equals(monHoc.getName())) {
                id_mon_hoc = monHoc.getId();
                break;
            }
        }
        int id_giao_vien = 0;
        for (GiaoVien giaoVien : dsGiaoVien) {
            if (ten_giao_vien.equals(giaoVien.getName())) {
                id_giao_vien = giaoVien.getId();
                break;
            }
        }
        try {
            String sql = "INSERT INTO `tkb_mh`"
                    + "(`id_mon_hoc`, `min_sv`, `max_sv`, `time_start`, `so_phong`, `id_giao_vien`, `so_tuan_hoc`) "
                    + "VALUES ('" + id_mon_hoc + "','" + min_sv + "','"
                    + max_sv + "','" + time_start + "','" + so_phong + "','"
                    + id_giao_vien + "','" + so_tuan_hoc + "')";
            services.Services.post(sql);
            fetchData();
            txtMinHS.setText("");
            txtMaxHS.setText("");
            txtTimeStart.setText("");
            txtSoPhong.setText("");
            txtSoTuan.setText("");
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Môn học đã được tạo, hãy chọn môn khác",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnAddItemActionPerformed

    public void fetchData() {
        // TODO add your handling code here:

        dsTKBMH = new ArrayList<>();
        try {
            String sql = "SELECT tkb_mh.id,min_sv,max_sv,time_start,so_phong,so_tuan_hoc,"
                    + " mon_hoc.name as \"ten_mon_hoc\", giao_vien.name as \"ten_giao_vien\" "
                    + "FROM `tkb_mh` INNER JOIN mon_hoc on tkb_mh.id_mon_hoc = mon_hoc.id "
                    + "INNER JOIN giao_vien ON tkb_mh.id_giao_vien = giao_vien.id";
            ResultSet rs = services.Services.get(sql);
            TKBMH x = null;
            while (rs.next()) {
                x = new TKBMH(rs.getInt("tkb_mh.id"), rs.getString("ten_mon_hoc"),
                        rs.getInt("min_sv"), rs.getInt("max_sv"), rs.getString("time_start"),
                        rs.getString("so_phong"), rs.getString("ten_giao_vien"),
                        rs.getInt("so_tuan_hoc"));
                dsTKBMH.add(x);
            }
            LoadTableSchedule();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ScheduleScreen scheduleScreen = new ScheduleScreen();
                scheduleScreen = (ScheduleScreen)ProtectScreen.protectScreen(scheduleScreen);
                scheduleScreen = (ScheduleScreen) CenterScreen.centerWindow(scheduleScreen);
                scheduleScreen.setTitle("Tạo thời khóa biểu cho môn học");
                scheduleScreen.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JComboBox<String> cbGiaoVien;
    private javax.swing.JComboBox<String> cbMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTKBMH;
    private javax.swing.JTextField txtMaxHS;
    private javax.swing.JTextField txtMinHS;
    private javax.swing.JTextField txtSoPhong;
    private javax.swing.JTextField txtSoTuan;
    private javax.swing.JTextField txtTimeStart;
    // End of variables declaration//GEN-END:variables
}
