/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package view.Student_DangKy;

import TableView.TableTKBMH;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.TKBMH;
import utilis.BackHome;
import utilis.CenterScreen;
import utilis.Global;
import utilis.ProtectScreen;

/**
 *
 * @author Doan Cuong
 */
public class DangKyScreen extends javax.swing.JFrame {

    ArrayList<TKBMH> dsTKBMH = new ArrayList<>();

    /**
     * Creates new form DangKyScreen
     */
    public DangKyScreen() {
        initComponents();
    }

    public void LoadTableDangKy() {
        tableTKBMH.setModel(new TableTKBMH(dsTKBMH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTKBMH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tableTKBMH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tableTKBMH.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(tableTKBMH);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Danh sách các môn đang mở");

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDangKy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDangKy.setText("Đăng ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(59, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnDangKy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(btnBack))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnDangKy)))
                                .addContainerGap(77, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        BackHome.client(this);
    }// GEN-LAST:event_btnBackActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        try {
            int row = tableTKBMH.getSelectedRow();
            // lấy id của môn cần đăng kí
            int id_tkbmh;
            id_tkbmh = (int) tableTKBMH.getModel().getValueAt(row, 0);
            int id_sv = Global.idLogin;
            try {
                String sql = "INSERT INTO `sv_tkbmh`(`id_sv`, `id_tkbmh`) VALUES ('"
                        + id_sv + "','" + id_tkbmh + "')";
                services.Services.post(sql);
                JOptionPane.showMessageDialog(this, "Đăng kí thành công, quay lại xem thời khóa biểu ",
                        "Thông báo", JOptionPane.DEFAULT_OPTION);
                fetchData();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Bạn đã đăng kí lớp học này, không thể đăng kí tiếp !",
                        "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Yêu cầu chọn môn để đăng kí",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnDangKyActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fetchData();
    }// GEN-LAST:event_formWindowOpened

    public void fetchData() {
        dsTKBMH = new ArrayList<>();
        try {
            String sql = "SELECT tkb_mh.id,min_sv,max_sv,time_start,so_phong,so_tuan_hoc,"
                    + " mon_hoc.name as \"ten_mon_hoc\", giao_vien.name as \"ten_giao_vien\" "
                    + "FROM `tkb_mh` INNER JOIN mon_hoc on tkb_mh.id_mon_hoc = mon_hoc.id "
                    + "INNER JOIN giao_vien ON tkb_mh.id_giao_vien = giao_vien.id";
            ResultSet rs = services.Services.get(sql);
            TKBMH x = null;
            while (rs.next()) {
                x = new TKBMH(rs.getInt("tkb_mh.id"), rs.getString("ten_mon_hoc"),
                        rs.getInt("min_sv"), rs.getInt("max_sv"), rs.getString("time_start"),
                        rs.getString("so_phong"), rs.getString("ten_giao_vien"),
                        rs.getInt("so_tuan_hoc"));
                dsTKBMH.add(x);
            }
            LoadTableDangKy();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không hợp lệ",
                    "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangKyScreen dangKyScreen = new DangKyScreen();
                dangKyScreen = (DangKyScreen) ProtectScreen.protectScreen(dangKyScreen);
                dangKyScreen.setVisible(true);
                dangKyScreen = (DangKyScreen) CenterScreen.centerWindow(dangKyScreen);
                dangKyScreen.setTitle("Đăng kí môn học");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDangKy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTKBMH;
    // End of variables declaration//GEN-END:variables
}
